spring:
  profiles:
    include:
      - vw-core

logging:
  level:
    com.mangkyu.openfeign.app.openfeign: DEBUG # feign에 대한 로깅 수준을 DEBUG로 설정 (가장 상세한 로그를 출력)

---
# 개발 (dev) 프로파일
spring:
  config:
    activate:
      on-profile: dev

---
# 스테이징 (staging) 프로파일
spring:
  config:
    activate:
      on-profile: staging

---
# 운영 (production) 프로파일
spring:
  config:
    activate:
      on-profile: production
