spring:
  profiles:
    include:
      - vw-core
  cache:
    type:
      redis # 캐시 타입을 redis로 지정
    redis:
      cache-null-values: true # 캐시에 null 값도 저장
  data:
    redis:
      host: ${REDIS_HOST:localhost} # Redis 호스트 주소 설정 (환경 변수가 설정되지 않은 경우 기본값 localhost)
      port: ${REDIS_PORT:6379} # Redis 포트 번호 설정 (환경 변수가 설정되지 않은 경우 기본값 6379)
      password: ${REDIS_PASSWORD:} # Redis에 접속할 때 사용할 비밀번호 설정 (환경 변수가 설정되지 않은 경우 기본값 빈 문자열)
logging:
  level:
    com.mangkyu.openfeign.app.openfeign: DEBUG # feign에 대한 로깅 수준을 DEBUG로 설정 (가장 상세한 로그를 출력)

---
# 개발 (dev) 프로파일
spring:
  config:
    activate:
      on-profile: dev

---
# 스테이징 (staging) 프로파일
spring:
  config:
    activate:
      on-profile: staging

---
# 운영 (production) 프로파일
spring:
  config:
    activate:
      on-profile: production
