spring:
  profiles: # 프로파일 설정
    include: # 다른 멀티 모듈 내의 프로파일 포함하도록 지정
      - vw-core
  cache: # 캐시 설정
    type: redis # 캐시 타입 redis로 지정
    redis:
      cache-null-values: true # 캐시에 null 값도 저장
  data: # 데이터 설정
    redis:
      host: ${REDIS_HOST:localhost} # Redis 호스트 주소 설정 (환경 변수가 설정되지 않은 경우 기본값 localhost)
      port: ${REDIS_PORT:6379} # Redis 포트 번호 설정 (환경 변수가 설정되지 않은 경우 기본값 6379)
      password: ${REDIS_PASSWORD:} # Redis에 접속할 때 사용할 비밀번호 설정 (환경 변수가 설정되지 않은 경우 기본값 빈 문자열)
  main:
    web-application-type: servlet # 어플리케이션이 어떤 형태로 동작할지 지정 (서블릿 기반)
logging: # 로깅 설정
  level:
    com.mangkyu.openfeign.app.openfeign: ${LOGGING_LEVEL:DEBUG} # feign에 대한 로깅 수준 설정