name: CI&CD Pipeline # Github Actions의 workflow 이름 정의

on:
  push:
    branches:
      - master # 이벤트 트리거 설정 : master에 푸시할 때 동작

# 실행 환경 설정
jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ] # 동일한 workflow를 여러 가지 다른 환경에서 실행시킴

    steps:
      # 레포지토리를 체크아웃하여 워크스페이스에 가져옴
      - name: Check Out The Repository
        uses: actions/checkout@v3

      # Java 환경 설정
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'corretto'

      # 버전 정보 추출
      - name: Get the version
        id: get_version
        run: |
          RELEASE_VERSION_WITHOUT_V="$(cut -d'v' -f2 <<< ${GITHUB_REF#refs/*/})"
          echo ::set-output name=VERSION::$RELEASE_VERSION_WITHOUT_V

      # Gradle 캐싱 설정
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # gradlew 스크립트에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # Spotless 코드 포매터를 실행해 코드 스타일 확인
      - name: Check spotless
        run: ./gradlew spotlessCheck

      # github secret의 값을 통해 dockerfile 갱신
      - name: Update dockerfile
        run: |
          cat dockerfile > dockerfile.temp
          
          echo "ENV DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> dockerfile.temp
          echo "ENV DOCKERHUB_NAME=${{ secrets.DOCKERHUB_NAME }}" >> dockerfile.temp
          echo "ENV DOCKERHUB_PORT=${{ secrets.DOCKERHUB_PORT }}" >> dockerfile.temp
          echo "ENV RDS_ENDPOINT=${{ secrets.RDS_ENDPOINT }}" >> dockerfile.temp
          echo "ENV RDS_PORT=${{ secrets.RDS_PORT }}" >> dockerfile.temp
          echo "ENV CUSTOM_EMAIL_ADDRESS=${{ secrets.CUSTOM_EMAIL_ADDRESS }}" >> dockerfile.temp
          echo "ENV CUSTOM_EMAIL_EMAIL=${{ secrets.CUSTOM_EMAIL_EMAIL }}" >> dockerfile.temp
          echo "ENV CUSTOM_EMAIL_NAME=${{ secrets.CUSTOM_EMAIL_NAME }}" >> dockerfile.temp
          echo "ENV JPA_BATCH_FETCH_SIZE=${{ secrets.JPA_BATCH_FETCH_SIZE }}" >> dockerfile.temp
          echo "ENV JPA_DDL_AUTO=${{ secrets.JPA_DDL_AUTO }}" >> dockerfile.temp
          echo "ENV JPA_DETER_DATASOURCE_INITIALIZATION=${{ secrets.JPA_DETER_DATASOURCE_INITIALIZATION }}" >> dockerfile.temp
          echo "ENV JPA_FORMAT_SQL=${{ secrets.JPA_FORMAT_SQL }}" >> dockerfile.temp
          echo "ENV JPA_SHOW_SQL=${{ secrets.JPA_SHOW_SQL }}" >> dockerfile.temp
          echo "ENV LOGGING_LEVEL=${{ secrets.LOGGING_LEVEL }}" >> dockerfile.temp
          echo "ENV RDS_DB_NAME=${{ secrets.RDS_DB_NAME }}" >> dockerfile.temp
          echo "ENV RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}" >> dockerfile.temp
          echo "ENV RDS_USERNAME=${{ secrets.RDS_USERNAME }}" >> dockerfile.temp
          echo "ENV REDIS_HOST=${{ secrets.REDIS_HOST }}" >> dockerfile.temp
          echo "ENV REDIS_PORT=${{ secrets.REDIS_PORT }}" >> dockerfile.temp
          echo "ENV REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> dockerfile.temp
          echo "ENV SQL_INIT_MODE=${{ secrets.SQL_INIT_MODE }}" >> dockerfile.temp
          echo "ENV MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> dockerfile.temp
          echo "ENV MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> dockerfile.temp
          
          mv dockerfile.temp dockerfile

        working-directory: ./vw-api

      # Gradle로 vw-api 모듈 빌드
      - name: Execute Gradle build
        run: ./gradlew :vw-api:build --no-daemon

      # Docker 빌드 툴인 Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Hub에 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker 이미지 빌드 및 Docker Hub에 푸시
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./vw-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_NAME }}

      # 빌드된 Docker 이미지의 디제스트 값 출력
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # EC2 인스턴스 내에서 Docker 컨테이너를 실행하여 애플리케이션을 실행
      - name: Application Run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 이전에 실행 중인 도커 컨테이너 중지
            sudo docker stop ${{ secrets.DOCKERHUB_NAME }}
            
            # 이전에 실행 중인 도커 컨테이너 강제로 삭제
            sudo docker rm -f ${{ secrets.DOCKERHUB_NAME }}
            
            # 최신 도커 이미지를 Docker Hub에서 EC2 인스턴스로 가져옴
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_NAME }}:latest
            
            # 새로운 도커 컨테이너 실행
            sudo docker run -p ${{ secrets.DOCKERHUB_PORT }}:8080 \
              --name ${{ secrets.DOCKERHUB_NAME }} \
              -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_NAME }}

      # gradlew 스크립트 권한 변경
      - name: gradlew permission change
        run: sudo chmod 755 gradlew

      # Sonaqube 분석
      - name: Sonaqube Analysis
        run: ./gradlew test sonarqube
          -Dsonar.host.url=${{ secrets.SONARQUBE_URL }}
          -Dsonar.projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }}
          -Dsonar.projectName=${{ secrets.SONARQUBE_PROJECT_KEY }}-${{github.event.pull_request.number}}
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}